### ISSUE TITLE
Unable to rotate images using asynchronous method

### ISSUE THREAD

**Issue by radiodario** [olokobayusuf/NatCam-Test-Suite#1]
Hi there,

I'm using natcam and i'm noticing the pictures i take are rotated 90 degrees (they're selfies but they're being uploaded in landscape)

Natcam reports the orientation correctly `Orientation.Rotation_90`, when the photo is taken, which i later use to rotate the photo appropriately before uploading to my server.

However, I tried using your ConcurrentDispatch method (As stated in the docs) but the callback never gets called. It works fine if i do it synchronously, but then my UI freezes for a second (which is not acceptable at this stage)

I'm using the exact same code as on the docs.

Is this a known issue?

**Comment by olokobayusuf** [comment]
> Is this a known issue?

It might be related to [this](https://forum.unity3d.com/threads/natcam-webcam-api.374690/page-21#post-3049117) issue.

**Comment by radiodario** [comment]
Hey, I think it's not related to that. It's working fine when I don't use the `ConcurrentDispatch`, but it isn't working when I try to do it using the background thread.

**Comment by olokobayusuf** [comment]
Are you not getting any exceptions?
