### ISSUE TITLE
Preview image has "washed out" look compared to the captured image

### ISSUE THREAD

**Issue by radiodario** [olokobayusuf/NatCam-Test-Suite#2]
Hi there, I'm seeing an issue where the preview image looks washed out compared to the captured photo. This is the case in the example `miniCam` as well as my own implementations.

Is this a known issue, or is there a way to ensure the preview resembles the captured picture as much as possible? I've tested it on iphone 6 and iphone 7plus

## Preview
![img_3505](https://user-images.githubusercontent.com/780409/28569765-21d9b1d4-7133-11e7-9bdc-86749c2d317b.PNG)

## Captured photo
![img_3506](https://user-images.githubusercontent.com/780409/28569764-21d78f94-7133-11e7-93d8-cc2e0df5ce61.PNG)

(please excuse my sleepy face hahaha)

Thanks

Dario

**Comment by olokobayusuf** [comment]
Hi Dario. NatCam doesn't do anything that could alter the picture quality of the preview vs the image. I presume that for photo capture, AVFoundation (iOS camera API) automatically performs some adjustments.

I've seen something similar in Live Photos. The 'live' animation of frames generally looks washed out compared to the final photo.
